"""empty message

Revision ID: 45efb31195bc
Revises: 30dda6ca48d0
Create Date: 2023-12-17 19:50:48.230313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45efb31195bc'
down_revision = '30dda6ca48d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
