"""empty message

Revision ID: a58fe813e2b3
Revises: d5a8140e1df6
Create Date: 2023-12-18 22:02:45.705799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58fe813e2b3'
down_revision = 'd5a8140e1df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('given_name', sa.String(length=500), nullable=True),
    sa.Column('family_name', sa.String(length=500), nullable=True),
    sa.Column('accounts', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
